### ISSUE TITLE
bug: Callbacks are not triggered

### ISSUE THREAD

**Issue by Mikkoun** [robingenz/capacitor-firebase-authentication#78] opened 2021-09-02 14:00 UTC
**Plugin version:**
@robingenz/capacitor-firebase-authentication@0.3.9
firebase@9.0.0

**Platform(s):**
Android
iOS

**Current behavior:**
When successfully signing in with `FirebaseAuthentication.signInWithGoogle()` the promise resolves but none of the event listeners fire. I tested firebase `onAuthStateChanged` and `onIdTokenChanged` callbacks and also `FirebaseAuthentication.addListener("authStateChange", ...)`.  When I skipped native auth and tried to sign in through firebase js sdk with the id token then firebase `signInWithCredential` function just froze and did not resolve. 
Everything works correctly in web implementation.

**Expected behavior:**
All the callbacks should trigger after successful sign in.

**Steps to reproduce:**
- Listen to `firebase.auth().onAuthStateChanged` callback
- Sign in to google with `FirebaseAuthentication.signInWithGoogle()`

**Related code:**
When I tried to sign in with firebase js sdk, signInWithCredential function just hangs and I did not reach "signInWithCredential finished" console log.
```
FirebaseAuthentication.signInWithGoogle()
      .then(async (response: SignInResult) => {
        const credential = firebase.auth.GoogleAuthProvider.credential(
          response.credential?.idToken
        );

        const authResult = await firebase
          .auth()
          .signInWithCredential(credential)
          .catch((err) => {
            console.debug("AUTH ERROR", err);
          });

        console.debug("signInWithCredential finished", authResult);
      })
      .catch((error) => {
        dispatchToast(t("start.methods.error_generic"));
        console.debug("FirebaseAuthentication.catch", error);
      })
      .finally(() => {
        console.debug("FirebaseAuthentication.finally");
        setLoading(false);
      });
```

Callback that did not trigger:
```
FirebaseAuthentication.addListener("authStateChange", (stateChange) => {
      console.debug("FirebaseAuthentication authStateChange", stateChange);
});
```

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.2
  @capacitor/core: 3.2.2
  @capacitor/android: 3.2.2
  @capacitor/ios: 3.2.2

Installed Dependencies:

  @capacitor/cli: 3.2.0
  @capacitor/ios: 3.2.0
  @capacitor/core: 3.2.0
  @capacitor/android: 3.2.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment] 2021-09-02 20:24
Thank you for your request!

If you are using `skipNativeAuth` to sign up the user via the Firebase JS SDK, then `addListener('authStateChange', ...).addListener('authStateChange', ...)` will not work on Android and iOS because it uses the native listener implementation. In that case, you need to use the Firebase JS SDK ([onauthstatechanged](https://firebase.google.com/docs/reference/js/v8/firebase.auth.Auth#onauthstatechanged)) directly.


As far as I can see, you are using the syntax of `firebase@^8.0.0` but using `firebase@9.0.0`.
Firebase JS SDK 9 has several major changes.
The [`firebase-js-sdk.md`](https://github.com/robingenz/capacitor-firebase-authentication/blob/main/docs/firebase-js-sdk.md) uses `firebase@8.10.0` in the `Examples` section.
I will be update these examples this weekend (see #79).
Maybe this has confused you.

The following should work:

```js
import { FirebaseAuthentication } from '@robingenz/capacitor-firebase-authentication';
import { GoogleAuthProvider, signInWithCredential } from "firebase/auth";

const signInWithGoogle = async () => {
  // Firebase JS SDK must be initialized first.
  // See https://firebase.google.com/docs/web/setup

  // Register listener
  const auth = getAuth();
  auth.onAuthStateChanged(user => console.log(user));

  // Sign-in using the plugin
  const result = await FirebaseAuthentication.signInWithGoogle();

  // Sign in using the Firebase JS SDK
  const credential = GoogleAuthProvider.credential(result.credential?.idToken);
  const result = await signInWithCredential(credential);
};
```


I have not tested the example right now. It may contain syntax errors.

Let me know if it works!

**Comment by robingenz** [comment] 2021-09-04 10:17
I have updated the [`firebase-js-sdk.md`](https://github.com/robingenz/capacitor-firebase-authentication/blob/main/docs/firebase-js-sdk.md) (see #82).

**Comment by Mikkoun** [comment] 2021-09-09 06:46
I replaced `firebase/compat` to new firebase 9 syntax just like in your examples but `signInWithCredential` stays loading forever :/ No idea how to go forward with this bug but I'm pretty sure it is not your plugins fault.

**Comment by robingenz** [comment] 2021-09-09 15:35
Mhm that's weird 🤔 In that case, I need a minimal, reproducible example that I can debug to help you further.

**Comment by roldyclark** [comment] 2021-09-15 12:24
I have the same issue, signInWithCredential never returns on iOS. 
code example:
```
export const googleLogin = async () => {
  // 1. Create credentials on the native layer
  const result = await FirebaseAuthentication.signInWithGoogle()
  // 2. Sign in on the web layer using the id token
  const credential = GoogleAuthProvider.credential(result.credential?.idToken)
  const auth = getAuth()
  await signInWithCredential(auth, credential)
    .then((response) => console.log(response))
    .catch((err) => console.log(err))
}
```
Thank you for this plugin btw this is the closest I've gotten to getting this working!

**Comment by robingenz** [comment] 2021-09-15 16:59
@roldyclark Can you please share some more information?
- iOS version and Device
- npm dependencies and versions (`package.json`)
- Run `npx cap doctor` in a terminal and paste the output

**Comment by roldyclark** [comment] 2021-09-15 17:43
# iOS version and Device
iPhone 8 iOS 14.5 (Xcode simulator)

# package.json
{
  "name": "svelte-app",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "rollup -c",
    "dev": "rollup -c -w",
    "start": "sirv public --no-clear",
    "check": "svelte-check --tsconfig ./tsconfig.json"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^17.0.0",
    "@rollup/plugin-json": "^4.1.0",
    "@rollup/plugin-node-resolve": "^11.0.0",
    "@rollup/plugin-replace": "^3.0.0",
    "@rollup/plugin-typescript": "^8.0.0",
    "@tsconfig/svelte": "^2.0.0",
    "@types/halfmoon": "^1.0.1",
    "firebase": "^9.0.2",
    "prettier": "^2.3.2",
    "prettier-plugin-svelte": "^2.4.0",
    "rollup": "^2.3.4",
    "rollup-plugin-livereload": "^2.0.0",
    "rollup-plugin-svelte": "^7.0.0",
    "rollup-plugin-terser": "^7.0.0",
    "svelte": "^3.0.0",
    "svelte-check": "^2.0.0",
    "svelte-preprocess": "^4.0.0",
    "tslib": "^2.0.0",
    "typescript": "^4.4.2"
  },
  "dependencies": {
    "@capacitor/android": "^3.2.2",
    "@capacitor/browser": "^1.0.3",
    "@capacitor/cli": "^3.2.2",
    "@capacitor/core": "^3.2.2",
    "@capacitor/geolocation": "^1.1.0",
    "@capacitor/ios": "^3.2.2",
    "@capacitor/share": "^1.0.4",
    "@capacitor/storage": "^1.1.0",
    "@robingenz/capacitor-firebase-authentication": "^0.3.10",
    "dotenv": "^10.0.0",
    "halfmoon": "^1.1.1",
    "postcss": "^8.3.6",
    "rollup-plugin-postcss": "^4.0.1",
    "rxfire": "^6.0.1",
    "rxjs": "^7.3.0",
    "sirv-cli": "^1.0.0",
    "svelte-awesome": "^2.3.2",
    "svelte-environment-variables": "^1.0.4"
  }
}

#  Capacitor Doctor  

Latest Dependencies:

  @capacitor/cli: 3.2.3
  @capacitor/core: 3.2.3
  @capacitor/android: 3.2.3
  @capacitor/ios: 3.2.3

Installed Dependencies:

  @capacitor/cli: 3.2.2
  @capacitor/core: 3.2.2
  @capacitor/android: 3.2.2
  @capacitor/ios: 3.2.2

[success] iOS looking great! 👌

**Comment by robingenz** [comment] 2021-09-15 17:46
@roldyclark  Thank you! Have you also tested it on a real iOS device? If not, could you do that?

**Comment by roldyclark** [comment] 2021-09-15 17:47
@robingenz sure thing, I'll try now - thanks!

**Comment by roldyclark** [comment] 2021-09-15 18:18
Tried on physical iPhone 8, 14.7.1. Same thing. The user is created in Firebase console, but the promise is never resolved.

**Comment by robingenz** [comment] 2021-09-15 18:26
Thank you! I will try to reproduce the problem again this weekend. I was not able to reproduce it on Android.
Please note that `signInWithCredential` is not a method of this plugin. This plugin only generates the input parameters. I will check if the input parameters are correct. If this is the case, you have to report the error in [firebase/firebase-js-sdk](https://github.com/firebase/firebase-js-sdk).

**Comment by roldyclark** [comment] 2021-09-15 18:30
@robingenz Yeah seems like it's a Firebase issue. Thanks for looking into it!

**Comment by roldyclark** [comment] 2021-09-17 07:42
@robingenz  update: no Firebase JS SDK calls are working on iOS. await getDocs() is hanging too. Should I not be using the JS SDK? What are the alternatives?

**Comment by robingenz** [comment] 2021-09-17 14:55
@roldyclark Thanks for the update. In that case I assume that the problem has nothing to do with this plugin and I close the issue.

> Should I not be using the JS SDK? What are the alternatives?

If you don't really need the Firebase JS SDK on Android and iOS and the methods of this plugin offer you the functionality you need, then I wouldn't use it either.

If you do want to use the Firebase JS SDK, I recommend you try the [compat libraries](https://firebase.google.com/docs/web/modular-upgrade). Maybe these work better.

**Closed by robingenz** 2021-09-17 14:55 UTC
Labels: needs: reproduction

**Comment by roldyclark** [comment] 2021-09-21 14:40
FIXED! Here's the solution: https://harryherskowitz.com/2021/08/23/firebase-capacitor.html

**Comment by mostafa3ly** [comment] 2022-02-12 19:03
@roldyclark 
I can't view the solution can u share it again so i can use it please 
Thank you

**Comment by roldyclark** [comment] 2022-02-13 20:40
@mostafa3ly whoops my domain expired, just fixed might be a sec for it to show up.

**Comment by mostafa3ly** [comment] 2022-02-14 10:12
@roldyclark
is `addListener('authStateChange', ...) ` called with you cause it never been called with me in `skipNative ` `true `or `false` on android and iOS and i can't understand it's purpose on plugin
