### ISSUE TITLE
bug: unable to signInWithCredential using plugin with angular fire

### ISSUE THREAD

**Issue by mpkasp** [robingenz/capacitor-firebase-authentication#104] opened 2021-11-24 01:41 UTC
**Plugin version:** ^0.3.11

**Platform(s):** iOS

**Current behavior:** At a loss as to what's going on. Google sign in is successful and giving a result with an idToken, but calling `this.afAuth.signInWithCredential` never resolves. I'm not sure if I'm passing a bad object or what. I'm using this plugin with firebase and angular fire:

```
"@angular/fire": "^7.1.1",
"@robingenz/capacitor-firebase-authentication": "^0.3.11",
"firebase": "^9.5.0",
```

**Expected behavior:** signInWithCredential resolves

**Steps to reproduce:**

```js
    const result = await FirebaseAuthentication.signInWithGoogle();
    console.log('[login] signed in', result);
    const credential = GoogleAuthProvider.credential(result.credential?.idToken);

    this.afAuth.signInWithCredential(credential).then(uc => {
      console.log('[login] success: ', uc);
    }, err => {
      console.log('[login] error: ', err);
    }).catch(err => console.log('[login] cred caught error', err));
```

**Other information:**
Possibly not a bug with this plugin, but really not sure what's going on here. Found some similar issues googling around to no resolve and hoping someone else has ideas.

**Capacitor doctor:**
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.3.2
  @capacitor/core: 3.3.2
  @capacitor/android: 3.3.2
  @capacitor/ios: 3.3.2

Installed Dependencies:

  @capacitor/cli: 3.2.5
  @capacitor/core: 3.2.5
  @capacitor/android: 3.2.5
  @capacitor/ios: 3.2.5

[success] iOS looking great! 👌
[success] Android looking great! 👌

```

**Comment by robingenz** [comment] 2021-11-24 10:09
Hi @mpkasp,
thank you for your request and for filling out the issue template. 
This issue seems like a duplicate of #78. For this reason, I am closing this Issue.
This was apparently the solution: https://github.com/robingenz/capacitor-firebase-authentication/issues/78#issuecomment-924055336
Let me know if that helps you.

**Closed by robingenz** 2021-11-24 10:09 UTC
Labels: duplicate

**Comment by mpkasp** [comment] 2021-11-24 20:47
Ok, dove a bit deeper & it looked like the difference of using Angular Fire may be the culprit because I tore it out and now that I'm using the js firebase SDK directly everything seems to be working now.

Hopefully this helps someone else.

**Comment by robingenz** [comment] 2021-11-24 21:01
Thank you for this update.
https://github.com/angular/angularfire/issues/2979#issuecomment-940910213 shows how this works with Angular Fire.

**Comment by mpkasp** [comment] 2021-11-29 01:33
Thanks, I fought with that briefly to no avail and ended up just pulling out angular fire - wasn't too bad fortunately due to abstraction :)
