### ISSUE TITLE
bug: Issue with Facebook SignIn accessToken

### ISSUE THREAD

**Issue by preet-pal** [robingenz/capacitor-firebase-authentication#145] opened 2022-03-17 13:05 UTC
**Plugin version:**
0.4.3

**Platform(s):**
Capacitor Apps

**Current behavior:**
The Facebook authentication doesn't work.

**Expected behavior:**
Facebook authentication should work as expected.

**Steps to reproduce:**
Try using `signInWithFacebook` function and it will result in no acessToken in the response.

So, instead the `await FirebaseAuthentication.signInWithFacebook()` returns idToken which I instead used to authenticate the user. The response from the `signInWithFacebook` function didn't have `accessToken` at all.

**Comment by robingenz** [comment] 2022-03-17 14:34
Closed as duplicate of #136

**Closed by robingenz** 2022-03-17 14:34 UTC
Labels: duplicate
