### ISSUE TITLE
bug: iOS Sign in Not Persisting

### ISSUE THREAD

**Issue by jayp0521** [robingenz/capacitor-firebase-authentication#131] opened 2022-02-03 02:36 UTC
**Plugin version:**
 @robingenz/capacitor-firebase-authentication@latest

**Platform(s):**

**Current behavior:**

I am using Google and Apple Sign In. Both sign in options seem to work fine on web. However on iOS, the sign in works, but drops off if I do `window.location.reload()` or restart the app.

I am seeing this in the output, but have no idea what it means. Unable to debug where it is coming from.

**Expected behavior:**
Sign in should persist after app restart

**Steps to reproduce:**

1. Sign in with Google
2. Restart App
3. Sign in is prompted again

**Related code:**

```
function providerFinder(
    providerName: string,
) {
    switch (providerName) {
        case 'google':
            return async () => {
                // 1. Create credentials on the native layer
                const result = await FirebaseAuthentication.signInWithGoogle()
                // 2. Sign in on the web layer using the id token
                const credential = GoogleAuthProvider.credential(result.credential?.idToken)
                const auth = getAuth()
                await signInWithCredential(auth, credential)
                return result
            }
        case 'apple':
            return async () => {
                // 1. Create credentials on the native layer
                const result = await FirebaseAuthentication.signInWithApple()
                // 2. Sign in on the web layer using the id token and nonce
                const provider = new OAuthProvider('apple.com')
                const credential = provider.credential({
                    idToken: result.credential?.idToken,
                    rawNonce: result.credential?.nonce,
                })
                const auth = getAuth()
                await signInWithCredential(auth, credential)
                return result
            }
        default:
            throw new Error('Login Type is not Supported.')
    }
}
```

**Other information:**
I see this in xcode output:
```
⚡️  TO JS ERROR MESSAGE:  {"code":"UNIMPLEMENTED","errorMessage":"not implemented","message":"not implemented"}
undefined
```

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.0
  @capacitor/core: 3.4.0
  @capacitor/android: 3.4.0
  @capacitor/ios: 3.4.0

Installed Dependencies:

  @capacitor/cli: 3.4.0
  @capacitor/android: 3.4.0
  @capacitor/ios: 3.4.0
  @capacitor/core: 3.4.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment] 2022-02-03 07:57
Hi @jayp0521,
this issue seems like a duplicate of #109.
For this reason i'm closing this issue.
Please let me know if the problem persists. Then I will open the issue again.

**Closed by robingenz** 2022-02-03 07:57 UTC
