### ISSUE TITLE
bug: `addListener('authStateChange', ...)` callback is never get called

### ISSUE THREAD

**Issue by mostafa3ly** [robingenz/capacitor-firebase-authentication#132] opened 2022-02-12 18:12 UTC
**Plugin version:**

@robingenz/capacitor-firebase-authentication version ^0.4.1

**Platform(s):**

iOS
Android

**Current behavior:**

`addListener('authStateChange', ...)` is never get called on iOS or android with neither `skipNativeAuth` `true `or `false ` and working fine on web
so what it's purpose in the plugin

i initialize my app with this code and export auth used in whole app from the `initalizeAuth ` function

```
const app = initializeApp(FIREBASE_CONFIGS);

export const auth = Capacitor.isNativePlatform()
  ? initializeAuth(app, {persistence: indexedDBLocalPersistence})
  : getAuth(app);

**Comment by robingenz** [comment] 2022-02-14 11:06
Hi @mostafa3ly,
sorry for the late reply. I am very busy at the moment. I'll look at your issue this week.

**Comment by mostafa3ly** [comment] 2022-02-24 17:15
I have Web , Android and iOS apps for my application using Ionic React and Capacitor.
the plugin is working fine on **web** version for each sign in method and the firebase JS sdk `onAuthStateChanged` function is working perfectly so it can listen to the auth state and on **web** also the plugin listener `addListener("authStateChange",...)` is working perfectly and can listen to the auth state.

but when testing the application on **Android**  the firebase JS sdk `onAuthStateChanged` function is working perfectly 
and the plugin function `addListener("authStateChange",...)` is not working as expected or as i understand its purpose it never get called when i enter the application on first time and also it never get called when i sign in with Google but the sign in with the plugin method `FirebaseAuthentication.signInWithGoogle()` is success and i know that this is login on the native layer so i link it with js layer after login with firebase JS sdk `signInWithCredential()` and `onAuthStateChanged` is now updated with the logged in user but the plugin function is never updated that is what i can't know its purpose in the plugin

i expected from this plugin listener to be get updated and called when the user changed on Android application so i will not need to have JS sdk implementation and use the plugin full auth system

and when i implement this on iOS the Google sign is worked fine but it open the native google dialog twice i think this because of first time is for  `FirebaseAuthentication.signInWithGoogle()` and second for `signInWithCredential()`

i try this with skipNativeAuth both true and false

**Comment by robingenz** [comment] 2022-02-25 18:41
As I said before, it works fine in my demo app (on all platforms). Please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) in a GitHub repo so i can debug it.

**Comment by aogorek** [comment] 2022-02-26 15:03
@robingenz I had same issues, so I forked project and tried to figure it out.
The problem is that **'authStateChange' event IS fired** but it is called before the listener is registered, so the result in logs is that no listener is registered and it is ignored. 
It looks like capacitor plugin is registered before angular app is initialized, then constructor of FirebaseAuthentication is called. It initializes listeners and event is fired immediately.

In my fork i temporarily moved initialization of listeners to  FirebaseAuthenticationPlugin#addListener method, so it is called after my listener was registered and it started working properly.
Very dirty solution, but works for now.
You may take a look:
https://github.com/aogorek/capacitor-firebase-authentication
Code is dirty, because I'm still testing solutions (also with logging with email and password), but you can see what I mean.

**Comment by mostafa3ly** [comment] 2022-02-28 18:37
i think my implementation was wrong i fixed it and it working as expected but i have another issue 


when signing in with facebook the result is `{provider:..., idToken:...} `and there is no accessToken  which is used in `signInWithCredential`

**Comment by robingenz** [comment] 2022-02-28 18:53
@mostafa3ly Thanks for letting us know. Please create a new issue and fill in the bug template.

Since the actual problem `addListener('authStateChange', ...) is never get called` does not seem to be a bug, I will close this issue. 

@aogorek Yes, it is not yet documented how to configure the demo app (see https://github.com/robingenz/capacitor-firebase-authentication-demo/issues/2). I will do that in a timely manner. If you manage to create a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) in a GitHub repo, please open a new issue and let me know so I can debug the issue.

**Closed by robingenz** 2022-02-28 18:53 UTC
Labels: needs: reproduction
